
id: functional-requirements
title: Functional Requirements
description: |
  This section describes the functional requirements associated with a specific 
  feature. Each functional requirement specifies functions that a system or 
  component must be able to perform and that must be present for the user 
  to be able to use the services provided by the feature.
sections: 
  - id: overall-description
    title: Overall Description
    description: 
      "Pryv.io is a middleware which aims to provide personal data management.
      As a middleware, Pryv.io does not provide User Interfaces (UI), nor physical storage or infrastructure.
      The system is composed of a few components being:

      1. One to several core components: responsible for the core functionalities like data storage, access control.

      2.	Two to several register component: responsible for linking a data subject’s storage to the corresponding core component responsible for the data management."
  - id: connectivity-and-interfaces
    reqid: CON
    title: Connectivity and interfaces
    requirements: 
      - reqid: HTTP
        title: The system shall be accessible through an HTTP API
        description: Access to the system is done using a Web API.

  - id: data-types
    reqid: DATA
    title: Data Types
    requirements: 
      - reqid: DEFTYPE
        title: The system shall provide default data types.
        description: Default data types are available in the system.

      - reqid: CUSTTYPE
        title: The system shall accept custom data types.
        description: It is possible to define custom data types.
      
      - reqid: CUSTVAL
        title: The system shall allow to define custom type validation.
        description: It is possible to define validation rules for custom-defined types.

  - id: streams
    reqid: STREAM
    title: Streams
    description: 
      "See: [/concepts/#streams](/concepts/#streams)"
    requirements:
      - reqid: 01
        title: A
        description: B
  

