
id: functional-requirements
title: Functional Requirements 
description: |
  This section describes the functional requirements associated with a specific 
  feature. Each functional requirement specifies functions that a system or 
  component must be able to perform and that must be present for the user 
  to be able to use the services provided by the feature.
sections: 
  - id: overall-description
    title: Overall Description
    description:
      "Pryv.io is a middleware which aims to provide personal data management.
      As a middleware, Pryv.io does not provide User Interfaces (UI), nor physical storage or infrastructure.
      The system is composed of a few components being:

      1. One to several core components: responsible for the core functionalities like data storage, access control.

      2.	Two to several register components: responsible for linking a data subject’s storage to the corresponding core component responsible for the data management."

  - id: connectivity-and-interfaces
    reqid: CON
    title: Connectivity and interfaces
    requirements: 
      - reqid: HTTP
        title: The system shall be accessible through an HTTP API
        description: Access to the system is done using a Web API.
        refs: 
          - url: http://api.pryv.com
            description: Pryv HTTP is described online at http://api.pryv.com

  - id: data-types
    reqid: DATA
    title: Data Types
    requirements: 
      - reqid: DEFTYPE
        title: The system shall provide default data types.
        description: Default data types are available in the system.

      - reqid: CUSTTYPE
        title: The system shall accept custom data types.
        description: It is possible to define custom data types.
      
      - reqid: CUSTVAL
        title: The system shall allow to define custom type validation.
        description: It is possible to define validation rules for custom-defined types.

  - id: streams
    reqid: STREAM
    title: Streams
    description: 
      "See: [/concepts/#streams](/concepts/#streams)"
    requirements:
      - reqid: BASE
        title: The system shall permit stream management through the specified actions.
        description: |
          The following actions are provided by the system to manage Streams.
          - Create 
          - Read 
          - Edit 
          - Delete 
          - Share

  - id: events
    reqid: EVENT
    title: Events
    description: 
      "See: [/concepts/#events](/concepts/#events)"
    requirements:
      - reqid: BASE
        title: The system shall permit events management through the specified actions.
        description: |
          The following actions are provided by the system to manage Events. 
          - Create
          - Read
          - Edit
          - Delete

  - id: dlc
    reqid: DLC
    title: Data life cycle management
    description: 
      "Each part of the life cycle is further described."
    requirements:
      - reqid: BASE
        title: The system shall manage all data life cycle parts as described here.
        description: | 
          The following actions are provided by the system to manage Streams.
          1.	Collect and aggregate
          2.	Structure and store 
          3.	Use 
          4.	Share
          5.	Archive
          6.	Disposal
    
    sections:
      - id: collect
        title: Collect
        requirements:
          - reqid: COLLECT
            title: The system shall allow data input through multiple sources.
            description: | 
              The following actions are provided by the system to manage Streams.
              -	Web services
              -	IoT and other mobile devices
              - Electronic records

      - id: store
        title: Store
        requirements:
          - reqid: STORE
            title: The system shall ensure data integrity. 
            description: | 
              The system ensures the data entered in the system is kept and 
              transmitted in its original form.

      - id: use
        title: Use and aggregate
        requirements:
          - reqid: USE
            title: The system shall provide data retrieval and aggregation from different sources
            description: | 
              The system provides retrieval of data independently from the source with a   
              **Selection by**:
                - Time 
                - Modification date
                - Stream
                - Tag
                - Deletion state

          - reqid: AGG
            title: The system shall provide methods to aggregate data from multiple subjects
            description: | 
              The model of streams and events is designed for merging data from multiple subjects


      - id: archiving
        title: Archiving and disposal
        requirements:
          - reqid: DEL
            title: The system shall ensure deletion of data
            description: |
              The system provides the following informations to check the existence of an item:
              - Deleted state
              - Complete deletion
              - Track of deleted items for synchronization

          - reqid: MOVE
            ignore: true
            title: The system shall ensure that a subject and all its data can be moved to another core component (intra-system migration).
            description: | 
              ""

          - reqid: EXPORT
            title: The system shall provide the possibility to export all the subjects’ data out of the system (extra-system migration).
            description: | 
              The system provides export capability and tools to export all data of a subject. The exported format facilitates interoperability.


  - id: access
    reqid: ACC
    title: Access Control
    requirements:
      - reqid: SELECT
        title: The system shall provide granular access per data subject.
        description: | 
          The system provides the following limitation properties to accesses 
          - Streams list
          - Tag list 
          - Expiration date
          
          Read and Write levels are provided at a Stream level

      - reqid: CONTRACT
        title: The system shall provide storage of contractual terms relative an Access.
        description: | 
          The system provides extra properties for each Accesses to store contractual terms. These terms should be relative to the limitation of an Access. If terms are displayed to user during an Access request flow and accepted by the User, the contractual terms stored are a proof of Consent.

      - reqid: ENFORCE
        title: The system shall enforce access control.
        description: | 
          The system
          - denies invalid or expired access
          - authorizes valid access based on their limitation properties

      - reqid: BASE
        title: The system shall manage access control given by the subject to access its data.
        description: | 
          The following actions are provided by the system to manage Accesses
          - Create
          - List
          - Update
          - Delete

      - reqid: REQUEST
        title: The system shall provide the external services (App) to request access to data by means of access control.
        description: | 
          Access request and enforcement flow involves the following actors with specific actions: 
          - **App**: Request, Obtain
          - **Data Subject**: Accept, Deny
          - **System**: Check, Enforce

      - reqid: TYPE
        title: The system shall provide Personal, App and Shared type of access.
        description: The system provides Personal, Apps and Shared Access
        references: 
          refs:
            - url: http://api.pryv.com/concepts/#accesses
              description: Access concept description

      - reqid: DELEGATE
        title: The system shall provide delegation of access control
        description: | 
          - **Personal** can manage App and Shared accesses
          - **App** 
            - can create Shared accesses within their scope
            - can manage created Shard accesses

      - reqid: REGISTER
        title: The system shall provide management for received access at a user level
        description: |
          The system provides **Followed Slices** to manage received access
          - Create
          - Update 
          - Delete
          - List
        refs:
            - url: https://l.rec.la:4443/reference-full/#followed-slices
              description: Followed Slices api documentation

  - id: notifications
    reqid: NOTIF
    title: Notifications
    requirements:
      - reqid: EVENT
        title: The system shall provide notification capabilities for changes at Event level.
        description: |
          The system provides an **Event change** notification when the following occurs at Event level
            - Creation
            - Modification
            - Deletion 

      - reqid: STREAM
        title: The system shall provide notification capabilities for changes at Stream level.
        description: |
          The system provides a **Structure change** notification when the following occurs at Stream level
            - Creation
            - Modification
            - Deletion 

      - reqid: LISTEN
        title: The system shall provide listener registration capabilities
        description: |
          The system provides a web socket based implementation to register a listner 

  - id: user
    reqid: USER
    title: User management
    requirements:
      - reqid: BASE
        title: The system shall permit user management through the specified actions.
        description: |
          The following actions are provided by the system to manage Users
            - Creation
            - Deletion 

      - reqid: LOGIN
        title: The system shall provide authentication of user on a login / password pair
        description: |
          The system provides authentication on login with a userid/password pair

      - reqid: LOGOUT
        title: The system shall provide login out
        description: |
          The system provides invalidation of authorization resulting in a login out

      - reqid: EMAIL
        title: The system shall provide email property management
        description: |
          The system provides email property management at a User level 
          - at creation of user
          - an API call to change the email property of a user

      - reqid: EMAILID
        title: The system shall provide retrieval of userId from an email
        description: |
          The system provides discovery of userId by email

      - reqid: LIST
        title: The system shall provide a list of users (data subject)
        description: |
          The system provides a list of users registered on the platform with the following properties:
          - registration date
          - invitation token used
      
    sections:
      - id: invitations
        reqid: INV
        title: Invitations
        requirements: 
          - reqid: BASE
            title: The system shall provide limitations to register to the platform
            description: |
              The system provides a use-once invitation tokens
          
          - reqid: LIST
            title: The system shall provide a list of invitation tokens
            description: The system provides a list of invitation tokens and their validity

          - reqid: GEN
            title: The system shall provide a generation of new invitations tokens
            description: The system provides a generation of new invitations tokens with a title

          - reqid: MANY
            title: The system shall provide use-many invitation tokens
            description: The system can take a list of invitation tokens that can be used with no limitations.

      - id: profile
        reqid: PROFILE
        title: Profile
        requirements: 
          - reqid: PRIVATE
            title: The system shall provide a storage of properties at a private user level
            description: The system provides storage of key/value pairs at user account level only available for Personal access

          - reqid: PUBLIC
            title: The system shall provide a storage of properties at a public user level
            description: The system provides storage of key/value pairs at user account level available publicly 

          - reqid: APP
            title: The system shall provide a storage of properties at an App access user level
            description: The system provides storage of key/value pairs at app level only available by App access

  - id: system
    reqid: SYSTEM
    title: System requirements
    sections:
      - id: hardware
        reqid: HWRE
        title: Hardware
        requirements: 
          - reqid: OS
            title: The system shall run on UNIX system
            description: 
              "The following UNIX system are supported:
                - Ubuntu Server 16.04 LTS"

          - requid: CONTAINER
            tiltle: The system should be packaged in a container for shipment and deployment.
            description: The system is delivered packaged in **Docker** container
            refs:
              - url: https://www.docker.com/
                description: Docker.com web site


  - id: non-functional
    title: Non-Functional Requirements
    sections:
      - id: security
        reqid: SEC
        title: Security
        requirements: 
          - reqid: NOAUTH
            title: The system shall store in a log file non-authorized API calls
            description: 
              "Refusal of access are logged on the hosting operating system using syslog"

          - reqid: AUTH
            tiltle: The system shall store in a log file authorized API calls
            description: Authorized accesses are logged on the hosting operating system using syslog with mechanisms to identify the used Access token.

          - reqid: COM
            title: The system shall provide encryption of all Inboud communications
            description: The system is provided with a component ensuring SSL termination. This component can be replaced by the customer. 

          - reqid: ENC
            title: The system shall provide mechanisms for client-side encryption
            description: The data model supports client-side encryption by encapsulating encrypted data into `encrypted/*` data types.
            refs:
              - url: http://api.pryv.com/event-types/#encrypted
                description: Encrypted data-type reference

      - id: audit
        reqid: AUDIT
        title: Auditability
        requirements: 
            - reqid: AUTHOR
              title: The system shall provide auditability of data edition. 
              description: 
                Events, Streams and Access exposes the date of modifications and the Access token used. The aim is to be able to answer the what and when questions, taken a specific who.

            - reqid: CALLS
              title: The system shall provide auditability of all API calls by Access token 
              description: 
                All HTTP calls POST, PUT, GET, DELETE are logged on the hosting operating system using syslog with mechanisms to identify the used Access token. The aim is to be able to answer the what and when questions, taken a specific who.
      
      - id: recoverability
        reqid: BCKP
        title: Recoverability
        requirements: 
            - reqid: BASE
              title: The system shall be able to be fully recovered using the latest backup available.  
              description: 
                Data not backed up shall not be taken into accounts in the need of recoverability.



          
                    


      

       





      





  

