#!/bin/sh

# This script sets up the Pryv API documentation build environment

# working dir fix
scriptsFolder=$(cd $(dirname "$0"); pwd)
cd $scriptsFolder/..

# check for well known prereqs that might be missing
hash node 2>&- || { echo >&2 "I require Node.js"; exit 1; }
hash just 2>&- || { echo >&2 "I require 'just'"; exit 1; }


# setup test-results repo copy
if [ ! -d dependencies/test-results ]
then
  echo "Setting up 'source/test-results/_source' folder for test-results dependency."
  git clone git@github.com:pryv/test-results-pryv.io.git dependencies/test-results
fi

# ensure test-results repo copy is up-to-date
cd dependencies/test-results
git checkout master
git pull
yarn install
cd $scriptsFolder/..

# setup service-core repo copy
if [ ! -d dependencies/core ]
then
  echo "Setting up 'source/event-types/_source' folder for service-core dependency."
  git clone git@github.com:pryv/service-core.git dependencies/core
fi

coreBranch="master"

echo "Service-core dependency is targeting the following branch: $coreBranch"

# ensure service-core repo copy is up-to-date
cd dependencies/core
git checkout $coreBranch
git pull
echo "Installing Node modules from 'package.json' if necessary."
just install-stable
echo "Creating dist."
just compile-release


cd $scriptsFolder/..

# install this repository's dependencies
just install

# setup build folder
if [ ! -d build ]
then
  echo "Setting up 'build' folder for publishing to GitHub pages."
  git clone git@github.com:pryv/pryv.github.io.git build
fi

echo "


If no errors were listed above, the setup is complete.
See the README for more info on writing and publishing.
"
