#!/bin/sh
set -e

# Sets up the Pryv API documentation build environment

# working dir fix
scriptsFolder=$(cd $(dirname "$0"); pwd)
cd $scriptsFolder/..

# check for well known prereqs that might be missing
hash node 2>&- || { echo >&2 "I require Node.js"; exit 1; }
hash just 2>&- || { echo >&2 "I require 'just'"; exit 1; }

# setup git pre-commit hook if appropriate ($CI is "true" in GitHub workflows)
PRE_COMMIT="scripts/pre-commit"
if [[ -d .git && "$CI" != "true" ]]; then
  cp $PRE_COMMIT .git/hooks/
  echo ""
  echo "Git pre-commit hook setup from '$PRE_COMMIT'"
  echo ""
fi

# –––––––––––––----------------------------------------------------------------
# Dependency: test-results repo copy
# –––––––––––––----------------------------------------------------------------

if [ ! -d dependencies/test-results ]
then
  echo ""
  echo "# test-results dependency: setting up repo copy..."
  echo ""
  git clone git@github.com:pryv/test-results-pryv.io.git dependencies/test-results
fi

echo ""
echo "# test-results dependency: checking out branch 'master'..."
echo ""
cd dependencies/test-results
git checkout master
git pull
yarn install
cd $scriptsFolder/..

# –––––––––––––----------------------------------------------------------------
# Dependency: service-core repo copy
# –––––––––––––----------------------------------------------------------------

if [ ! -d dependencies/core ]
then
  echo ""
  echo "# service-core dependency: setting up repo copy..."
  echo ""
  git clone git@github.com:pryv/service-core.git dependencies/core
fi

coreBranch="release/1.8"

echo ""
echo "# service-core dependency: checking out branch '$coreBranch'..."
echo ""

cd dependencies/core
git checkout $coreBranch
git pull

echo ""
echo "# service-core dependency: installing node modules if necessary..."
echo ""
just install-stable

echo ""
echo "# service-core dependency: compiling..."
echo ""
just compile-release

# –––––––––––––----------------------------------------------------------------
# Finally setup dev site build
# –––––––––––––----------------------------------------------------------------

cd $scriptsFolder/..

echo ""
echo "# Installing node modules if necessary..."
echo ""
npm install

# setup `dist/` folder
if [ ! -d dist ]
then
  echo ""
  echo "# Setting up 'dist/' folder for publishing to GitHub pages..."
  echo ""
  git clone git@github.com:pryv/pryv.github.io.git dist
fi

echo ""
echo "If no errors were listed above, the setup is complete."
echo "See the README for more info on writing and publishing."
echo ""
